name: Deploy Portfolio
run-name: ${{ github.actor }} is publishing out Portfolio
on: [push]
jobs:
  build:
    name: Deploying to surge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: ls
      - run: npm install
      - run: npm run build
      - uses: dswistowski/surge-sh-action@v1
        with:
          project: "./apps/resume/dist"
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
          domain: ${{ secrets.SURGE_DOMAIN }}
