name: Deploy Portfolio
run-name: ${{ github.actor }} is publishing out Portfolio
on: [push]
jobs:
  build:
    name: Deploying to surge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm install -g surge lerna
      - run: npx lerna run build
      - run: npm run build
      - run: ls
      - run: ls ./apps/resume/dist
      - run: surge ./ ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
